FROM python:3.12-slim-bookworm

# Set working directory inside the container
WORKDIR /app

# Copy all files from current folder (Challenge_1a) into container
COPY . .

# Install system-level dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libglib2.0-0 \
    swig \
    && rm -rf /var/lib/apt/lists/*

    # Install NLTK stopwords (and optionally punkt, wordnet, etc. if needed)
RUN python -m nltk.downloader stopwords

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run your module
CMD ["python", "-m", "src.main"]
